### ISSUE TITLE
unexpected error HTTP: 400

### ISSUE THREAD

**Issue by yanikucho** [tomlandia/fuckr#106]
It worked well all of yesterday, but then today, i got this error message when trying to log on, saying go to fuckr.me for updates. even not conected, it doesn't show profiles. 

[capture](https://cloud.githubusercontent.com/assets/25361088/22322281/d05cad32-e368-11e6-9406-2eb288f95477.PNG)

**Comment by RobbieTechie** [comment]
They shut down the v2 api, until v3 is released it won't work

**Comment by markbosshard** [comment]
but why is it possible to download the app now from www.fuckr.me? is that still the old apiv2 version? I thought you fixed it now..

**Comment by RobbieTechie** [comment]
@markbosshard 
The app is downloadable because this is @tomlandia github, and he has control over that.  He had just updated the app and updated that site.  Yes that is still the old v2 API and just a couple days ago, the team at grindr shut down that api.  You can no longer get the data from their servers for that API, so the app posted on fuckr.me is no longer functional.

I had done some updates based off his work, and had this thing up and functioning on the old v2.  I downloaded the v3 api branch, but have not got it fully functional.  I've made some progress but I'm not sure I'll be able to get the whole thing.  I am not totally familiar with Angularjs and right now I'm learning Angualr2 so I may work on writing a new version based on that.

The problem right now for me is that I'm not getting the app to verify it's authenticated so it will not display the chat or settings section.  When I debug it, in the console it tells me "login missing" yet it logs into the grindr server as I can see the profile on the actual grindr app.  I added instructions to tell it that it's authenticated but it still does not behave properly.  I have a feeling we will have to wait for @tomlandia to get it fully working as there seem to not be any other programmers here with the experience to help troubleshoot this, or they are remaining silent.

**Comment by markbosshard** [comment]
Thanks so much for this clear update on the status, @RobbieTechie! A pitty I do not have these skills either..
