### ISSUE TITLE
Messages does not arrive

### ISSUE THREAD

**Issue by victorgrego** [tomlandia/fuckr#12]
Looks like fuckr is not getting the messages. I have tested it extensively and it is not getting the messages that arrive. When I connect with app on my phone I get tons of messages. Maybe the interception is not working well.

Can u check this?

**Comment by Kav28** [comment]
From what I have observed fuckr gets the messages but they are still on the
grindr server so when you start the app on a device youll see all the
messages

**Comment by victorgrego** [comment]
here I am not receiving the messages on my fuckr desktop, just in the app

**Comment by tomlandia** [comment]
Odd... I just tested last version on Mac and it receives and doesn't get duplicates when reloading. If you launch Grindr on your phone while using Fuckr it should redirect you to login page.

The way it works:
- after login, GET /undeliveredChatMessages then POST /confirmChatMessagesDelivered
- while running, Fuckr receives XMPP messages with a custom pure-JS (hence supposed to work on all platforms) client then POST /confirmChatMessagesDelivered to acknowledge messages so you don't get dupes when reloading.

I'll test on Windows when I have the occasion.

**Comment by tomlandia** [comment]
Tried on Windows still don't see how to reproduce :/

**Comment by jwax33** [comment]
Having this problem intermittently as well since the update.  Sometimes it will simply stop receiving messages from Grindr.  Some users report not receiving messages being sent from Fuckr.  In my limited testing, when this was happening I could send messages to and from two Fuckr instances with no problems, but not between a Fuckr instance and a Grindr instance.  I will say, though, that regular Grindr users were also reporting some messaging issues so the problem may have been on Grindr's end.

**Comment by tomlandia** [comment]
I guess there was a Grindr outage but I improved offline error handling in v1.5 (just released).
