### ISSUE TITLE
403 forbidden, or filters having issues....info, updated filters/profile view

### ISSUE THREAD

**Issue by RobbieTechie** [tomlandia/fuckr#134]
So the team at grindr have been getting cranky.  They have now changed code on their server so that if you are using a free account and try to use the filters, only the free ones will work.  This would be the age, tribes and looking for filters.

The current version on fuckr.me does not have those, but does have the online and photo only, and both of those will not work on free accounts.  On tom's version the app will not throw errors, on the older releases I made, you could get a 403 forbidden error.  Right now the app defaults to photo only being on, so if you run the app and see nothing and that is checked, that is why, it will not allow that xtra feature.

Last week I updated my fork from @tomlandia current release to add the 6 drop down filters back in, and also updated the profile view to show more info when viewing profiles.  This way the releases will be more consistent as this version works fine under windows 10 now.

I believe grindr thinks this will get more people to sign up for xtra, but for me it has the exact opposite effect.  Personally I'm liking this app less and less as time goes on, and their service has gone down hill

I can say, that this somewhat locks things down in some ways, not in others. And that their server itself is not exactly "secure", but that isn't anything I am going to disclose here.

![grindr](https://cloud.githubusercontent.com/assets/23042713/24330722/d75a5036-11f2-11e7-8ebc-7f6471edd555.jpg)

**Comment by guynwpg** [comment]
This is most likely an overly noob question but where do I find your version with the 6 filters? If I access Fuckr via your profile, it shows the latest release as 1.81, rather than 2.0.0

**Comment by ssbbpp** [comment]
What you (all, together) have accomplished is really impressive. When the panic of apiv3 first appeared, i was hoping i'd have time to help, but i had a few personal issues soak up all available time and then some. So all i can do is express thanks and respect from the outside. I'm finally able to look at this once again, and I have a question or two as i set things up:
1, i saw your advice just to clone tomlandia's master and then zip-overwrite your files on top. But I'm confused that github asserts the following three facts:
       A. you're 14 committs ahead and 19 behind Tomland
       B. Tomlandia last committed code to his tree in February
       C. You last updated from the current release 3 weeks ago.
I think this implies that the current release branch is older by at least 15 commits from the current master. I cloned the current master a few days ago. Any idea if it's dangerous/dumb/painful or not a problem if I now zip-overwrite your code on top of the current master? If this merge would be useful to you, i'm happy to give it a try. (Just to spell it out, i used to write code for a living, but haven't for some time and never node.  I'd like to make the effort to get some skills back, just trying to estimate if this is a good way to do that, or a bad one. )
2. One of the things that pushed me to you guys in the first place is that grindr seems to explicitly prevent its own app from running on an intel or mac hardware, as well as on any virtual device. This isn't an API question -- as far as I can tell the code actually checks a few things and shuts down if it doesn't like the neighborhood it just came alive in. It's not a question of not wanting to run on emulation either, It wont start on any version of android-x86 running native either, and that's really android on metal, no emulation. I was just wondering if fuckr does anything to make grindr think it's actually real bona fide grindr code. Given how nasty they've been, actually including client code to make the client committ suicide rather than live on intel hardware, i was just wondering if you think you'll need to spend time at some point pretending to be running in an iOS or android phone.
i'll prob just try to brute-force add your code on top of the master branch right now, to see what happens.

Thanks again for this amazing work. I only hope that grindr doesn't prove to be a service that wasn't worthy of the attention from devs as talented as you all.....

**Comment by RobbieTechie** [comment]
I was actually about to close this as an issue, but I'll leave it a bit longer.  I'm not greatly familiar with github's functionality in detail.  When I forked this from the main branch, we were still on v2 of the api, which was version 1.8.0 or 1.8.1 of fuckr and we had to fix that for a bit back in October.  When I made adjustments, I simply uploaded files that I worked with directly to my github account.

When Thom fixed this version, he made some code changes and which were different from what I had worked with, and then he released his code for the different OSs Linux, Mac, and Windows.  Windows 10 did not like his code at first but was ok with mine, I so had left mine as the old version for a while.  Then with an update Win10 started to behave a little better.  I then updated my code from downloading the app from his site, and updating to add filters back in

The code from both accounts is in sync now, except that I've added back filters and updated the profile views.  Just to be clear, Thom is the author of this, and this version is still considered in alpha stage and has some issues.

As for grindr, they've become quite pissy about things, and now when you run the app, you need to remove the check marks from the online and photo only boxes, as those are paid filters, and grindr updated their code on their server to make sure those won't work unless you have grindr xtra (which isn't worth it imho).

Yes this is a great way to learn some things.  As for grindr, they have code that checks to see if this is runing in an android emulator, and it will close the app on most of them if (which has pissed quite a few potential customers off).  They believe they can protect their code by doing so, they've even gone as far as to obfuscate things with Dexguard.  In my opinion, that can only slow people down a little bit, there is no real security in the app.  They also keep bloating it up on Android and not telling people what they put in there.

One big reason I use Fuckr over that is the creepy shit they do.  They can tell how long you are in any spot, where you put your finger on your screen, how long you spend on any part, the times you interact in any way with the app, then they take all their analytics and sell that data to companies.  They also slam ads in everyones face for the most simple tasks in the app, which is ridiculous.  I've totally quit using grindr on android, and barely use it on the computer any more.

There is an unofficial API document on the main page here, if you want to dig through that, there is info in there that would answer some of the questions you've asked.
