### ISSUE TITLE
Mainstream maintained ?

### ISSUE THREAD

**Issue by mfld-fr** [tomlandia/fuckr#164]
Who is maintaining this project mainstream ? Is @tomlandia still active on it, or should one consider it as abandoned ?

In other words, is it worth to submit PR here, or better select another fork, like the one from @RobbieTechie, that provided active support in latest issues ?

**Comment by elfelround** [comment]
i wanna know too, also, a chatroom or mailing list of contributors to this project would be cool, presuming we are all gay coders

**Comment by RobbieTechie** [comment]
@mfld-fr At this point one could pretty much say it's been abandoned.  The pull requests have been sitting there since April, and @tomlandia doesn't appear to care much about it any longer.

@elfelround That would be a very incorrect presumption, most people here are not coders, and only come here when there are problems.  There are a few of us that still work on it, but most that I've talked to do a little bit, then quit talking, or when they get what they need, they just stop cold.

**Comment by elfelround** [comment]
i personally dont know coffee script, i was reading the process or rest calls etc detailed on the project and it looks quite cool

**Comment by mfld-fr** [comment]
@RobbieTechie : thanks for your response. Are you enough committed to this project so that we could consider your fork as a new mainstream to submit PR ?

**Comment by RobbieTechie** [comment]
Well I'm not opposed to updating my fork, yet at the same time I'm not trying to take this over from the original author.  I still consider this @tomlandia 's work.  If you wish to submit a PR be my guest.

**Comment by mfld-fr** [comment]
Initial question answered, thanks @RobbieTechie.
