### ISSUE TITLE
Take A Look From Reddit

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#177]
Take A Look From Reddit @victorgrego @shyrat @RobbieTechie @kav28

https://www.reddit.com/r/TweakBounty/comments/7q9zcy/301032_1112_grindr_app_enhancements/

**Comment by victorgrego** [comment]
Haha 30 bucks does not pay one hour of programming. Thanks for the heads up though.


--
Victor Nascimento
________________________________

**Comment by RobbieTechie** [comment]
While some of that is possible, most of what he is asking for is controlled server side and it not obtainable without paying for extra.  I'm not sure if people are aware but Grindr on the android side has not been updated since the 13th of December.  The company was also recently totally bought out https://techcrunch.com/2018/01/09/chinas-kunlun-completes-full-buyout-of-grindr/

**Comment by Grindr13** [comment]
Android 3.23.0 was released on 1/31. However, I don't believe that #157 will ever be resolved, thus rendering Fuckr totally unusable, except for a select group of people who know how to write their own code. The website fuckr.me should be taken down. The only thing that website lets you do is download a package that doesn't work.

> Closes #177

**Comment by Kav28** [comment]
There has been an android update this week - introduced an "explore"
feature and shuffled some option buttons
