### ISSUE TITLE
Missing RobbieTechie Added Filters V.1.80 (Looking For | Tribe | Ethnicity | Body Type | Position | Relationship Status) - 2017

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#42]
Hi @tomlandia thank you for your update, could @RobbieTechie collaborate with you possibly on his quick fix version. He had added all these filters ;-) Or tell me which part of the code / files I need to share and I'll send it over.

![2017-01-14_082442](https://cloud.githubusercontent.com/assets/16879733/21956305/00f69154-da33-11e6-93e3-31f9b4bf79ed.JPG)

**Comment by powline99** [comment]
Hi @tomlandia thank you for your update, could @RobbieTechie collaborate with you possibly on his quick fix version. He had added all these filters ;-) 

![2017-01-14_082442](https://cloud.githubusercontent.com/assets/16879733/21956305/00f69154-da33-11e6-93e3-31f9b4bf79ed.JPG)

**Comment by RobbieTechie** [comment]
@powline99 I messaged him about this, I'm guessing when he has a free bit of time, he will take care of it and add the relationship and position filters back.

**Comment by RobbieTechie** [comment]
@powline99 
I did this update from a fresh download of v1.81
https://drive.google.com/file/d/0BxSmknffFGTnUGgzUVFudkQzUVE/view?usp=sharing

**Comment by powline99** [comment]
@RobbieTechie Thank you Robbie, very kind of you! I appreciate your contribution and improvements! Excited about future collaborations between you and @tomlandia

**Comment by RobbieTechie** [comment]
@powline99 You're welcome.  Thank @tomlandia for the Metric to US update, that was all him.  As for the updates,  As far as the updates being forced, I'm not an Apple person, but friends have told me they are forced to update apps quite often, so that's a little more on Apple's end.  Grindr forced the update from v2 to v3 though.  

I am a bit curious what just got added, as the app just jumped from 6.8MB to 9.7MB going from 3.0.10 to 3.0.11 and as of last night they just updated to 3.0.12

**Comment by northstar77** [comment]
Hi @RobbieTechie, the files that you shared, are those all complete? For some reason when I replaced them on my Fuckr, nothing at all shows up. No profiles or anything. Page is completely blank.
