### ISSUE TITLE
Update to Grindr API v3 as v2 might stop working soon

### ISSUE THREAD

**Issue by tomlandia** [tomlandia/fuckr#63]
@shyrat @victorgrego I'm planning to look into v3 tomorrow (European time) using Genymotion with certificate pinning disabled, please let me know if you've already got something. Thanks 😃!

**Comment by shyrat** [comment]
Their anti-tampering is good; I've had a lot of trouble with this.  It looks like they paid for something professional like DexGuard.  I tried:

- MITM.  As you've noticed, certificate pinning.
- Disassembling the apk.  There's a few goodies in there, but most of it is lost to obfuscation.  In particular, string obfuscation means I can't readily calculate JSON payloads by looking at the source.
- Modifying the apk to remove the pinning check.  They have some anti-tampering code that detects if the apk isn't signed exactly by grindr, and shuts down the app.
- Running in an emulator.  They block emulators now.  (Even to the point of [pissing off their own customers](https://www.reddit.com/r/BlueStacks/comments/4uwgn9/app_crashes_as_soon_as_i_open_it/?st=irrw7n4f&sh=c07eee20).)

So far, all I have is a (possibly incomplete) list of v3 APIs, but no example of the JSON inputs for most.  I've only managed to MITM bootstrap and gcm-push-tokens so far.  As you can see, some of these look a lot like the v2 endpoints, but there's a bunch of exciting new stuff in here too.  (chat-pix? flags?).

```
/v3/bootstrap
/v3/broadcastMessages
/v3/flags/{id}
/v3/gcm-push-tokens
/v3/locations/{geohash}/profiles
/v3/managed-fields
/v3/me/blocks
/v3/me/blocks/{id}
/v3/me/chat/messages
/v3/me/conversations
/v3/me/conversations/{id}
/v3/me/favorites/{id}
/v3/me/pics
/v3/me/prefs
/v3/me/prefs/chat-pix/{hash}
/v3/me/prefs/phrases
/v3/me/profile
/v3/profiles
/v3/profiles/{id}
/v3/sessions
/v3/systemMessages
/v3/users
/v3/users/email
/v3/users/update-password
```

The official app uses https://grindr.mobi , although g3-beta.grindr.com seems to host the same services.  

I got a MITM of two APIs:
/v3/bootstrap is just a simple GET.  Only trick is getting a whitelisted useragent.
/v3/gcm-push-tokens looks like the same PUSH as in v2, so that's pretty boring.  Its inputs is:
`{ 
  "token":"(some long hash which I've redacted)",
  "vendorProvidedIdentifier":"(smaller hash)"
}`

Prior to authentication (for /v3/bootstrap), the official client sends these HTTP headers:
```
Accept: application/json
User-Agent: grindr3/3.0.1.4529;4529;Unknown;Android 4.4.4
Host: grindr.mobi
Connection: Keep-Alive
Accept-Encoding: gzip
```
Server responds to the official client with:
```
Date: (the date)
Content-Type: application/json
Content-Length: (length)
Connection: keep-alive
Set-Cookie: (a cloudflare cookie)
Cache-control: no-cache="set-cookie"
Content-Encoding: gzip
Set-Cookie: (an AWS cookie)
Vary: Accept-Encoding
X-Runtime: 0
Server: cloudflare-nginx
CF-RAY: (a cloudflare tracking id)
```

I have found one route to circumvent the certificate pinning, but I'd rather not discuss it publicly, lest that gets shut down too.  I'm trying to get ahold of a rooted phone running a particular OS version to make further progress.  Mail me at cody@shyrat.com and we can continue this discussion.

Another angle.  I haven't yet spent any time looking at the iOS version, because frankly, I don't know anything about iOS.  (I don't know anything about Android either, but in the last couple days I've gotten pretty good at faking it.)

**Comment by tomlandia** [comment]
Thanks!!! My guess is that the only solution is to use a real rooted/jailbroken device with one of these tools that disables certificate pinning by hooking the phone's native API. My email is ts@thomasschneider.com

**Comment by victorgrego** [comment]
I've collected some data through my rooted android phone using package collector in the phone, but got the same data presented by shyrat, if u guys want we could do a skype group chat where we could discuss the project progress. My skype is victorgrego if you guys feel like doing it.

**Comment by shyrat** [comment]
I got MITM working against 3.0.1.  I'll start writing up an API spec, and send a PR in a few hours.

**Comment by shyrat** [comment]
PR is #65 .  I'm too tired to keep going at the moment - I hope one of you can help fill out the blanks.  I haven't even begun looking at the XMPP side yet -- it's obvious that they added XEP-0333 but I don't know what else got changed from v2.

**Comment by tomlandia** [comment]
Made redundant by #89. WIP PR#90.

**Comment by genevera** [comment]
@shyrat @tomlandia would either of you mind sharing how you MITM'd this?  i've got it almost working and would rather try to implement your solution rather than hack away to reach the same end.

**Comment by ZeroFeetAway** [comment]
@genevera - email me? - hooburner@gmail.com

**Comment by kusaa** [comment]
@genevera  Have you been able to make any progress on this?

**Comment by slidster** [comment]
Guys!!!  Any update on this???
It's been over 3 weeks that I'm seeing:
"Temporarily unavailable due to Grindr APIv2 shutdown. Please come back in a week!"
when I go on Fuckr.me.

Great desktop app, We miss it!!

**Comment by penane** [comment]
APIv3 is working in KOPLAYER so there's a way to make it works on amulators

**Comment by Kav28** [comment]
Doesnt work for me - if I login with an existing account it says it cant
login, contact support and I cant create a new account. Am I missing
something?

**Comment by penane** [comment]
Did you tried the latest beta of KOPLAYER?

**Comment by Kav28** [comment]
Yes - then tried to login to my existing grindr account and got the
message. This is different behavior than bluestacks (where app gives
nothing) but then the usual behavior is for the app to load profile grid
and only ask for login when you try to view a profile

**Comment by ZeroFeetAway** [comment]
Perhaps KOPLAYER is working because it is using the actual app and valid user-agents.

**Comment by penane** [comment]
i'ts working pretty smooth for me. I don't know how to help you. Just 
installed koplayer, logged on google and run grindr.

**Comment by Kav28** [comment]
Have it working now.  I think it might be an issue with running on a phone
and then (a bit later) starting it with the same user in koplayer
