### ISSUE TITLE
HTTP 400 error

### ISSUE THREAD

**Issue by guynwpg** [tomlandia/fuckr#99]
Get this error when trying to log into  1.8.0 using the same log in I use for 1.7.0

I can still log into 1.7.0 no problem

**Comment by newtofuckr** [comment]
i am getting that error too. in fact, after i downloaded the new version, i was able to get online for the first time since May 2016. i even had some brief chat with 2 guys before the http 400 error kept appearing constantly (took about 5 times clicking ok before it cleared, i also saw something that said "primus grindr requires authentication" or something like that). and now i cant get online at all. the program WILL open, but everytime i try to connect, this error comes up. 

i read in an older thread somewhere, that someone said IF the account is created on fuckr, increases chances it will be banned by grindr. but if a person creates the account on their cell phone or smartphone, reduces the chances of a ban. can anyone confirm if this is true or not?

if this is true, i may try to create a "new" account on my phone and see how it goes. i personally prefer interacting on the computer. i dont know why grindr still wont create their own desktop version. 

i have never created a grindr account on my phone, always on fuckr, maybe this is why i keep getting error messages? :peace_symbol:

**Comment by dezertys** [comment]
Same thing, i just got it working for 10min then error http/400, allowing you to search for others but no message or profile setting. Does this error means Grindr banned the account?
My account was created by phone 1 year ago. By the way can someone share a line command that could update all fuckr/nw/npm/... versions and its depedencies?
Sorry for my English I'm French

**Comment by victorgrego** [comment]
Seems like since the latest update we are having ban issues. I was using the previous version, as soon as i updated i got banned

**Comment by RobbieTechie** [comment]
@victorgrego 
I don't think it's a ban issue, the v2 API has been fully shut down.
